### ISSUE TITLE
Create a DApp to allow users to send Avocado (AVO) tokens by email

### ISSUE THREAD

**Issue by peter-evans** [AvocadoNetwork/governance#6]
### Tasks
-  Create a DApp to allow users to send Avocado (AVO) tokens by email. The recipient should be able to receive the tokens for free, i.e. no transaction fees.

### Concept
1. The sender accesses a web interface (using MetaMask) and sends AVO to a smart contract along with a hash of the recipient's email address. A small amount of ETH should also be required for the transaction fee to the recipient.
2. An email is sent to the recipient with a link
3. The recipient clicks the link to access a web interface (using Metamask). If the recipient does not have a MetaMask wallet they should be guided to create one.
4. The recipient clicks "accept" and a transfer of the AVO is initiated by the backend server to the recipient's wallet address.

### Components
- Smart contract to keep the AVO and ETH in escrow
- Web interface to send and receive via MetaMask

### Testing
- AVO has a smart contract faucet on the Rinkeby testnet.
  See here for details: https://github.com/AvocadoNetwork/smart-contract-faucet

### Deliverables
- Fork [this repository](https://github.com/AvocadoNetwork/avocado-by-email) and submit a PR with the code. (We might change the name of the repository if there is a better name for the app!)
- Please deploy to Rinkeby so we can test it

### Timeframe
- Please aim to complete within 3 weeks.

### Reference
See here for information about AVO: https://github.com/AvocadoNetwork/governance/blob/master/README.md
Avocado icon:
https://github.com/AvocadoNetwork/media/blob/master/graphics/icon/avocado-icon.png

**Comment by agro1986** [comment]
Some ideas regarding how to store data on the smart contract:

* When sender wants to send AVO to receiver@gmail.com, the email address will be hashed using keccak256 on client side, and then it is stored as a key in the smart contract

e.g. if the email hash is "76e54fddf03e275cae7996df425bf1ad616fe1f079ea743f5c4fce83579562b1" and you want to send 100 AVO, then in the smart contract

balance["76e54fddf03e275cae7996df425bf1ad616fe1f079ea743f5c4fce83579562b1"] = 100

* When someone wants to claim their AVO, they will call a claim method in which the email address (unhashed) is one of the argument. The smart contract code will check whether the hash matches. Of course the server will do it in behalf of the receiver so that the receiver doesn't need to spend gas.

In essence someone's email address will be the key to get the AVO. If you have ideas to make it more secure (e.g., using additional salt) feel free to do it.

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 1000000.0 AVO  attached to it.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601).
 * Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $25,012.36 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by peter-evans** [comment]
@NFhbar I wondered if you would be interested in this task. You did such a great job with the faucet!

**Comment by NFhbar** [comment]
@peter-evans I would love to help but I won't have any time for a couple months; work is really busy right now. I'll show the bounty to some of my buddies, hopefully they'll be able to pick it up.

**Comment by benjaminmbrown** [comment]
Might be able to have one of our interns at ChainWave take a stab at this.

**Comment by peter-evans** [comment]
@benjaminmbrown That would be great!

**Comment by peter-evans** [comment]
I've increased the bounty on this task to 1000000 AVO.

**Comment by Gustavobelfort** [comment]
Is this bounty still open ? I like to help in it @peter-evans

**Comment by peter-evans** [comment]
@Gustavobelfort Yes, this bounty is still open. If you would like to work on this task please read the description and check that you are able to fulfill the requirements of the task. Let us know if you have any questions.

**Comment by felixwatts** [comment]
In reply to @agro1986 I don't think the scheme you outlined is secure. Once the claimant submits their unhashed email address to the network, a miner/validator receiving that information can front-run them and claim the AVO for themselves.

It can be made secure with the addition of one more step: The claimant first submits a transaction stating that they are about to claim the AVO. Their ethereum address is recorded in the smart contract. This only succeeds if no one else has made the same claim recently. Once the claimant sees that this transaction has succeeded they then make a second transaction submitting their unhashed email address. The smart contract only makes the AVO transfer if the ethereum address of the sender of the second transaction matches that of the first, and the second happens within a certain time limit of the first.

**Comment by peter-evans** [comment]
@pakokrew The proposed idea is that a small amount of ETH is required from the sender which will be kept at the contract address. This will be used to fund the transaction to the recipient.

**Comment by pacwoodson** [comment]
@peter-evans got it, but practically, the claimant must have to call the smart contract and pay transactions fees, right ? Or there's some kind of centralized backend which itself holds ETH to be able to call these methods (refunded by the ETH stored by the sender) ?

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 9 months, 3 weeks from now.
Please review their action plans below:


1. [LorenzoZaccagnini](https://gitcoin.co/profile/LorenzoZaccagnini) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?mutate_worker_action=approve&worker=LorenzoZaccagnini) | [reject worker](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?mutate_worker_action=reject&worker=LorenzoZaccagnini))_. 
    
    1. Create "email" smart contract with an interface for ERC20 AVO Token
2. The "email" smart contract will contain the hashes of the emails and the id of the generated link
3. When a user wants to send a token by email the smart contract takes the token from the ERC20 AVO (using approve and transfer from the ERC20), and adds them to a balance inside the "email" smart contract, using the target email and the link id as condition to withdraw the tokens later
4. For security reason will be implemented a backend to send the link to the target user

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601).

**Comment by gitcoinbot** [comment]
@LorenzoZaccagnini Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=1) | [3 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=3) | [5 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=5) | [10 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=10) | [100 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=100)

**Comment by gitcoinbot** [comment]
@LorenzoZaccagnini Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=1) | [3 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=3) | [5 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=5) | [10 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=10) | [100 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=100)

**Comment by gitcoinbot** [comment]
@LorenzoZaccagnini Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=1) | [3 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=3) | [5 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=5) | [10 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=10) | [100 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=100)

**Comment by gitcoinbot** [comment]
@LorenzoZaccagnini Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=1) | [3 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=3) | [5 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=5) | [10 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=10) | [100 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=100)

**Comment by gitcoinbot** [comment]
@LorenzoZaccagnini Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=1) | [3 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=3) | [5 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=5) | [10 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=10) | [100 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=100)

**Comment by gitcoinbot** [comment]
@LorenzoZaccagnini Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=1) | [3 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=3) | [5 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=5) | [10 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=10) | [100 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=100)

**Comment by gitcoinbot** [comment]
@LorenzoZaccagnini Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=1) | [3 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=3) | [5 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=5) | [10 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=10) | [100 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=100)

**Comment by gitcoinbot** [comment]
@LorenzoZaccagnini Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] warning (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=1) | [3 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=3) | [5 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=5) | [10 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=10) | [100 days](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601?snooze=100)

**Comment by peter-evans** [comment]
Changed the issue status of this task back to `open`.

**Comment by sameer2800** [comment]
@peter-evans, this is my idea on this. 
1)I will create a smart contract on which sender makes a request by entering the number of avo along with the hash of mail-id.  
2) the contract will also have a method which shows the balances of each hashed mail-address. 
3) I will provide another method for the recipient to verify whether his mail-address has any avo coins balance.
4) If recipient hashed mail-id is present in the list of balances, he can make a claim request to the contract ( this step is very much important , pls read @felixwatts 's comment above) . Once he claims, my smart contract locks avo coins to the receipent address for a pre-determined amount of time. this time is given by contract manager when he creates the contract.
5) Before the expiry time, the recipient has to provide email-address to the smart contract. the contract verifies the address of the recipient and compares email-id with hashed email-id.on success, releases the avo coins to the recipient.  

Note :: in my case, the recipient has to pay a small amount of gas to claim. my idea of not having any backend server is to reduce unnecessary claims.  Here , only receipent whose hashed-id is present in the available list can claim. sender can send the extra avo coins to the receipents for the transaction fee.

**Comment by peter-evans** [comment]
@sameer2800 A key point about this feature was that the recipient wouldn't need to pay transaction fees to receive the tokens. However, maybe that is a feature we could add later. Feel free to 'start work' on the Gitcoin page and I'll approve it.

**Comment by sameer2800** [comment]
@peter-evans  i am very much interested to work on this.  is it possible to get paid with ether ?

**Comment by peter-evans** [comment]
@sameer2800 At present we only pay out bounties in AVO tokens.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__Work has been started__.


These users each claimed they can complete the work by 3 months from now.
Please review their action plans below:


**1) [kpulkit29](https://gitcoin.co/profile/kpulkit29) has been approved to start work.**

I have been making dapps since a long time.Here is how I plan to make the project

1.Making UI and the smart contract
2.Testing email sending and token receiving,making backend routes

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601).

**Comment by kpulkit29** [comment]
Can I get some test ether on rinkeby
address is 
 0x0c8184C21a51CdB7Df9e5dc415a6A54b3A39C991

**Comment by kpulkit29** [comment]
I have written down the smart contract

**Comment by peter-evans** [comment]
@kpulkit29 You can request test ether on Rinkeby here: https://faucet.rinkeby.io/

**Comment by kpulkit29** [comment]
Smart contract tested and deployed to rinkeby.

**Comment by kpulkit29** [comment]
inpage.js:1 MetamaskInpageProvider - lost connection to MetaMask
TypeError: Cannot read property 'accounts' of undefined

**Comment by kpulkit29** [comment]
Due to this testing of contract becomes a little difficult do you know why metamask connection is getting lost

**Comment by kpulkit29** [comment]
It is mentioned in the description that an email is sent to the recipient and when he clicks accept backend server transfer AV.But backend cannot perform this task until and unless it know the address of the recipient so According to me he should be directed to a page which connects with metamask and that transaction fees required would be returned by to the recipient

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 1000000.0 AVO  has been submitted by__:

 1. [@kpulkit29](https://gitcoin.co/profile/kpulkit29)



@peter-evans please take a look at the submitted work:
* [PR](https://github.com/AvocadoNetwork/avocado-by-email/pull/1) by @kpulkit29

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $25,960.34 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by kpulkit29** [comment]
Kindly review the work

**Comment by kpulkit29** [comment]
Have added the changes to gitignore in the forked repository

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 1000000.0 AVO   attached to this issue has been approved & issued to @kpulkit29.__  

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $23,060.62 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 1000000.0 AVO   attached to this issue has been approved & issued to @kpulkit29.__  

 * Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/AvocadoNetwork/governance/6/601)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $23,060.62 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
